package com.iweb.panda.entity;

import java.util.Date;

public class UserDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Amounts
     *
     * @mbggenerated
     */
    private Double amounts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.City
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Coins
     *
     * @mbggenerated
     */
    private Integer coins;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.CreateTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.LastLoginTime
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.NickName
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.Sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.PaymentPwd
     *
     * @mbggenerated
     */
    private String paymentpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.UserType
     *
     * @mbggenerated
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.realName
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.idCard
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.empiricalValue
     *
     * @mbggenerated
     */
    private Integer empiricalvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.vipEmpiricalValue
     *
     * @mbggenerated
     */
    private Integer vipempiricalvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.diamond
     *
     * @mbggenerated
     */
    private Integer diamond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.visible
     *
     * @mbggenerated
     */
    private Boolean visible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.HeadImgUrl
     *
     * @mbggenerated
     */
    private String headimgurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ID
     *
     * @return the value of users.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ID
     *
     * @param id the value for users.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Amounts
     *
     * @return the value of users.Amounts
     *
     * @mbggenerated
     */
    public Double getAmounts() {
        return amounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Amounts
     *
     * @param amounts the value for users.Amounts
     *
     * @mbggenerated
     */
    public void setAmounts(Double amounts) {
        this.amounts = amounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.City
     *
     * @return the value of users.City
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.City
     *
     * @param city the value for users.City
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Coins
     *
     * @return the value of users.Coins
     *
     * @mbggenerated
     */
    public Integer getCoins() {
        return coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Coins
     *
     * @param coins the value for users.Coins
     *
     * @mbggenerated
     */
    public void setCoins(Integer coins) {
        this.coins = coins;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Country
     *
     * @return the value of users.Country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Country
     *
     * @param country the value for users.Country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.CreateTime
     *
     * @return the value of users.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.CreateTime
     *
     * @param createTime the value for users.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.LastLoginTime
     *
     * @return the value of users.LastLoginTime
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.LastLoginTime
     *
     * @param lastLoginTime the value for users.LastLoginTime
     *
     * @mbggenerated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Mobile
     *
     * @return the value of users.Mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Mobile
     *
     * @param mobile the value for users.Mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.NickName
     *
     * @return the value of users.NickName
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.NickName
     *
     * @param nickname the value for users.NickName
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Province
     *
     * @return the value of users.Province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Province
     *
     * @param province the value for users.Province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.Sex
     *
     * @return the value of users.Sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.Sex
     *
     * @param sex the value for users.Sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.PaymentPwd
     *
     * @return the value of users.PaymentPwd
     *
     * @mbggenerated
     */
    public String getPaymentpwd() {
        return paymentpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.PaymentPwd
     *
     * @param paymentpwd the value for users.PaymentPwd
     *
     * @mbggenerated
     */
    public void setPaymentpwd(String paymentpwd) {
        this.paymentpwd = paymentpwd == null ? null : paymentpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.UserType
     *
     * @return the value of users.UserType
     *
     * @mbggenerated
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.UserType
     *
     * @param usertype the value for users.UserType
     *
     * @mbggenerated
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.realName
     *
     * @return the value of users.realName
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.realName
     *
     * @param realname the value for users.realName
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.idCard
     *
     * @return the value of users.idCard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.idCard
     *
     * @param idcard the value for users.idCard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.state
     *
     * @return the value of users.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.state
     *
     * @param state the value for users.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.empiricalValue
     *
     * @return the value of users.empiricalValue
     *
     * @mbggenerated
     */
    public Integer getEmpiricalvalue() {
        return empiricalvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.empiricalValue
     *
     * @param empiricalvalue the value for users.empiricalValue
     *
     * @mbggenerated
     */
    public void setEmpiricalvalue(Integer empiricalvalue) {
        this.empiricalvalue = empiricalvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.vipEmpiricalValue
     *
     * @return the value of users.vipEmpiricalValue
     *
     * @mbggenerated
     */
    public Integer getVipempiricalvalue() {
        return vipempiricalvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.vipEmpiricalValue
     *
     * @param vipempiricalvalue the value for users.vipEmpiricalValue
     *
     * @mbggenerated
     */
    public void setVipempiricalvalue(Integer vipempiricalvalue) {
        this.vipempiricalvalue = vipempiricalvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.diamond
     *
     * @return the value of users.diamond
     *
     * @mbggenerated
     */
    public Integer getDiamond() {
        return diamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.diamond
     *
     * @param diamond the value for users.diamond
     *
     * @mbggenerated
     */
    public void setDiamond(Integer diamond) {
        this.diamond = diamond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.visible
     *
     * @return the value of users.visible
     *
     * @mbggenerated
     */
    public Boolean getVisible() {
        return visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.visible
     *
     * @param visible the value for users.visible
     *
     * @mbggenerated
     */
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sign
     *
     * @return the value of users.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sign
     *
     * @param sign the value for users.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.HeadImgUrl
     *
     * @return the value of users.HeadImgUrl
     *
     * @mbggenerated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.HeadImgUrl
     *
     * @param headimgurl the value for users.HeadImgUrl
     *
     * @mbggenerated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }
}